# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            evan bergeron
tagline:          nerd
url:              http://evanbergeron.github.io
paginate:         1
baseurl:          /
author:
  name:           Evan Bergeron
#  url:            https://twitter.com/mdo
  email:          bergeronej@gmail.com

# Custom vars
version:          1.0.2
github:
  repo:           https://github.com/poole/poole
pages_list:
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'
