# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Klekticist
tagline:          A Blog
url:              http://getpoole.com
paginate:         1
baseurl:          /
author:
  name:           Evan Bergeron
#  url:            https://twitter.com/mdo
  email:          bergeronej@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
